//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicosRX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int BillId { get; set; }
        public Nullable<int> DrId { get; set; }
        public Nullable<int> PatId { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<int> DR_Percentage { get; set; }
        public Nullable<int> Referal_Percentage { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
    }
}
