//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicosRX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiognasisTest
    {
        public int TestId { get; set; }
        public string TestName { get; set; }
        public string Description { get; set; }
        public bool IsChecked { get; set; }
    }
}
