//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicosRX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Pid { get; set; }
        public string PName { get; set; }
        public Nullable<int> PatientType { get; set; }
        public string ReferBy { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Date_of_Admission { get; set; }
        public Nullable<System.DateTime> Date_of_DisCharge { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatetedTime { get; set; }
    }
}
